spring:
  #数据源1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mariadb://172.16.26.167:3306/health?useAffectedRows=true
    #url: jdbc:mariadb://121.40.57.169:3306/health?useAffectedRows=true
    username: root
    password: root
#    druid:
#      # 开启慢SQL统计（这里超过10毫秒则判定为慢SQL）
#      filter:
#        stat:
#          enabled: true
#          log-slow-sql: true
#          low-sql-millis: 10
#      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#      filters: stat,wall,log4j2
#      use-global-data-source-stat: true
#      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#      ##### WebStatFilter配置 #######
#      web-stat-filter:
#        #启用StatFilter
#        enables: true
#        #添加过滤规则
#        url-pattern: /*
#        #排除一些不必要的url
#        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
#        #开启session统计功能
#        session-stat-enable: true
#        #缺省sessionStatMaxCount是1000个
#        session-stat-max-count: 1000
#      ##### StatViewServlet配置 #######
#      #启用内置的监控页面
#      stat-view-servlet:
#        enabled: true
#        #内置监控页面的地址
#        url-pattern: /druid/*
#        #关闭 Reset All 功能
#        reset-enable: false
#        #设置登录用户名
#        login-username: admin
#        #设置登录密码
#        login-password: 123
#        #白名单（如果allow没有配置或者为空，则允许所有访问）
#        allow:
#        #黑名单（deny优先于allow，如果在deny列表中，就算在allow列表中，也会被拒绝）
#        deny:
#      aop-patterns:
#        - com.yishi_app.dao.*

server:
  port: 8081

constant_server:
  photo_upload_path: /home/health/
  url_path: https://app.maillife.cn/files/
  chose_code: 1
  server_log: /home/health/script/logs
  #APNs推送是否为生产环境，false为开发环境
  apnsProduction: ture


mybatis:
  #mybatis中mapper文件的路径
  mapper-locations: classpath*:mappers/*.xml,classpath*:com/yishi_app/dao/**/*.xml
  #起别名。可省略写mybatis的xml中的resultType的全路径
  type-aliases-package: com.yishi_app.entity

  # knife开源的swagger ui配置
  #knife4j:
  #是否是生产环境，如果是生产环境会默认关闭swagger
#  production: true

sentry:
  enable: true
  dsn: http://f99d52dc170c4ab295c1aa084fbf0311@47.103.86.8:9000/6
  enable-tracing: true
  traces-sample-rate: 0.3

logging:
  level:
    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: WARN
  config: classpath:logback-spring.xml
